# Generated by Django 4.2.4 on 2023-10-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='total_reply',
            field=models.IntegerField(default=0),
        ),
    ]
