# Generated by Django 4.2.6 on 2023-10-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='date_added',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
