# Generated by Django 4.2.6 on 2023-10-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_forum_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='date_added',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
