# Generated by Django 4.2.6 on 2023-10-27 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('forum', '0002_rename_message_forum_description_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile'),
            preserve_default=False,
        ),
    ]
