# Generated by Django 4.2.6 on 2023-10-29 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forum_total_reply'),
        ('forum', '0003_alter_forum_date_added'),
    ]

    operations = [
    ]
