# Generated by Django 4.2.6 on 2023-10-27 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_forum_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='profile',
        ),
    ]
