# Generated by Django 4.2.6 on 2023-10-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('isbn10', models.IntegerField(blank=True, null=True)),
                ('isbn13', models.TextField(blank=True, null=True)),
                ('publish_date', models.TextField(blank=True, null=True)),
                ('edition', models.IntegerField(blank=True, null=True)),
                ('best_seller', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
