# Generated by Django 4.2.6 on 2023-10-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20231026_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
