# Generated by Django 4.2.6 on 2023-10-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20231029_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn10',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
