# Generated by Django 4.2.6 on 2023-11-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_isbn10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn10',
            field=models.TextField(blank=True, null=True),
        ),
    ]
