# Generated by Django 4.2.6 on 2023-10-27 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_rating'),
        ('book', '0004_auto_20231027_1521'),
    ]

    operations = [
    ]
