# Generated by Django 4.2.6 on 2023-10-25 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20231025_1413'),
    ]

    operations = [
    ]
